### ISSUE TITLE
Misleading terminology for contrast functions

### ISSUE THREAD

**Issue by nihil21** [simonavrillon/MUedit#1]
Hi, I would like to report an issue about the contrast functions in `lib/fixedpointalg.m` (lines 27--37): you are using g and g' in the FastICA iteration, whereas---according to [Hyvarinen](https://www.cs.helsinki.fi/u/ahyvarin/papers/NN00new.pdf)'s and [Francesco Negro](https://iopscience.iop.org/article/10.1088/1741-2560/13/2/026027)'s papers---you should use g' and g''. Therefore, what you are referring to as `square` is actually the **skewness**:
```
% G_skew(x) = x.^3 / 3
gp = @(x) 2*x;  % 2nd derivative
g = @(x) x.^2;  % 1st derivative
```
whereas what you are referring to as `skew` is actually the **kurtosis**:
```
% G_kurt(x) = x.^4 / 4
gp = @(x) 3*x;  % 2nd derivative
g = @(x) x.^3;  % 1st derivative
```

In the case of `logcosh`, what you are actually maximising is the **anti-derivative of logcosh** (which may make sense mathematically, but it is not commonly used for ICA and its effectiveness has not been proven). A better choice is to maximise the **actual logcosh**:
```
% G_logcosh(x) = log(cosh(x))
gp = @(x) 1 - tanh(x).^2;  % 2nd derivative
g = @(x) tanh(x);  % 1st derivative
```
You can verify the logcosh implementation by checking the [Scikit-learn's library](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/decomposition/_fastica.py#L141).

**Comment by simonavrillon** [comment]
Thanks for the contribution, the PR has been merged.
