### ISSUE TITLE
Pulsetrain dimensions don't match Dischargetime dimensions

### ISSUE THREAD

**Issue by agmccune** [simonavrillon/MUedit#4]
Hello- 

I am decomposing an HDemg signal and loading it into MU edit for manual editing and visualization of the motor units found. When analyzing the decomposed signal however I discovered that while the pulsetrain variable correctly contained 3xtime vectors representing the three identified motor units, the dischargetimes were a 7xtime array. I thought each row of the discharge time variable would represent a motor unit, but only three should have been present. Am I misidentifying the variable?

**Comment by simonavrillon** [comment]
No, you should have the same dimensions for both variables. Was the mismatch present after the decomposition or did you run into an error during the manual editing of the data?

**Comment by agmccune** [comment]
It occurred after I decomposed it using the hdemg_decomposition script, even in scripts I didn't edit, I loaded them into matlab and saw the discrepancy

**Comment by simonavrillon** [comment]
I've never seen this issue. Would you mind sending me a data sample by email to test the decomposition?

**Comment by simonavrillon** [comment]
The two variables had the same dimensions in the file.
